
name: CI/CD Pipeline for Exam Portal

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # FRONTEND
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # BACKEND
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build backend with Maven
      working-directory: ./backend
      run: mvn clean package -DskipTests

    # AWS Login
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # change as per your AWS region

