name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 🛠️ Backend build
      - name: Build Backend
        working-directory: ./backend
        run: mvn clean package -DskipTests

      # 🛠️ Frontend build
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # ✅ Docker build
      - name: Build Docker Images
        run: docker-compose build

      # ✅ Login to Docker Hub (optional)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push Docker Images
        run: |
          docker tag exam-backend yourdockerhub/exam-backend:latest
          docker tag exam-frontend yourdockerhub/exam-frontend:latest
          docker push yourdockerhub/exam-backend:latest
          docker push yourdockerhub/exam-frontend:latest
